import { existsSync, readFileSync } from 'node:fs';
import { genSecret } from './secrets.mjs';

/**
 * Parse a dotenv-style file into a plain object. Ignores comments and blanks.
 * Only used to recover previously generated secrets so restarts don't
 * invalidate existing sessions.
 */
function parseEnv(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

/**
 * Cloudflare Turnstile testing keys — always pass, never show a challenge.
 * https://developers.cloudflare.com/turnstile/troubleshooting/testing/
 */
const TURNSTILE_TEST_SITEKEY = '1x00000000000000000000AA';
const TURNSTILE_TEST_SECRET = '1x0000000000000000000000000000000AA';

/**
 * Build the dev env values for rvn-web and the WS server.
 *
 * Secrets (CSRF_SECRET, USER_DATA_SECRET, INTERNAL_API_KEY) are reused from
 * `existing` (the previous rvn-web .env.local) unless `fresh` is true, so that
 * a stack restart doesn't log everyone out.
 *
 * Returns { web: {...}, ws: {...} } — caller serializes to files.
 */
export function buildEnv({ existing = {}, fresh = false } = {}) {
  // Reuse an existing secret only if it still looks valid (≥32 chars, the
  // minimum env-validation accepts) — a hand-edited/corrupted value is
  // silently regenerated and reported back via `regenerated`.
  const regenerated = [];
  const keep = (name, gen) => {
    if (fresh) return gen();
    const val = existing[name];
    if (val && val.length >= 32) return val;
    if (val) regenerated.push(name);
    return gen();
  };

  const csrfSecret = keep('CSRF_SECRET', () => genSecret());
  const userDataSecret = keep('USER_DATA_SECRET', () => genSecret());
  const internalApiKey = keep('INTERNAL_API_KEY', () => genSecret());

  const web = {
    // --- Build-time (NEXT_PUBLIC_*) ---
    NEXT_PUBLIC_DOMAIN: 'http://localhost:3000',
    NEXT_PUBLIC_WS_URL: 'http://localhost:3002',
    NEXT_PUBLIC_TURNSTILE_SITEKEY: TURNSTILE_TEST_SITEKEY,

    // --- WebSocket (server-to-server) ---
    WEBSOCKET_SERVER_URL: 'http://localhost:3002',
    INTERNAL_API_KEY: internalApiKey,

    // --- Database (local Postgres) ---
    DATABASE_URL: 'postgresql://rvn:rvn@localhost:5432/rvn',

    // --- Redis (local, no TLS — so no REDIS_CERT_PATH) ---
    REDIS_URL: 'redis://localhost:6379',
    MEDIA_CACHE_ENABLED: 'true',
    MEDIA_CACHE_MAX_OBJECT_MB: '2',
    MEDIA_CACHE_TTL_SEC_SUPPORT: '3600',
    MEDIA_CACHE_TTL_SEC_AVATARS: '86400',

    // --- Security ---
    CSRF_SECRET: csrfSecret,
    USER_DATA_SECRET: userDataSecret,
    TURNSTILE_SECRET_KEY: TURNSTILE_TEST_SECRET,

    // --- S3 (local MinIO) ---
    S3_ENDPOINT: 'http://localhost:9000',
    S3_BUCKET: 'rvn',
    S3_ACCESS_KEY: 'minioadmin',
    S3_SECRET_KEY: 'minioadmin',
    S3_REGION: 'us-east-1',

    // --- Geolocation (runtime mmdb path; falls back to ip-api if absent) ---
    MAXMIND_DB_PATH: './database/GeoLite2-City.mmdb',

    // --- OAuth (disabled locally; pairs kept non-empty to satisfy validation) ---
    GOOGLE_CLIENT_ID: 'NONE',
    GOOGLE_CLIENT_SECRET: 'NONE',
    YANDEX_CLIENT_ID: 'NONE',
    YANDEX_CLIENT_SECRET: 'NONE',
    VK_CLIENT_ID: 'NONE',
    VK_CLIENT_SECRET: 'NONE',
    TWITCH_CLIENT_ID: 'NONE',
    TWITCH_CLIENT_SECRET: 'NONE',
    GITHUB_CLIENT_ID: 'NONE',
    GITHUB_CLIENT_SECRET: 'NONE',
    TELEGRAM_BOT_USERNAME: 'NONE',
    TELEGRAM_BOT_TOKEN: 'NONE',
  };

  const ws = {
    PORT: '3002',
    NODE_ENV: 'development',
    MAX_CLIENTS: '0',
    // WS runs in Docker, rvn-web runs on the host → reach it via host gateway.
    AUTH_SERVICE_URL: 'http://host.docker.internal:3000',
    INTERNAL_API_KEY: internalApiKey,
    CORS_ORIGINS: 'http://localhost:3000,http://localhost:3001',
  };

  return { web, ws, regenerated };
}

/** Serialize a flat env object to dotenv text with a leading banner. */
export function serializeEnv(values, banner) {
  const head = banner
    ? `# ${banner}\n# Generated by dev/up.mjs — do not edit by hand (changes are overwritten).\n\n`
    : '';
  return (
    head +
    Object.entries(values)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') +
    '\n'
  );
}

export { parseEnv };
