[package]
name = "image-processor-wasm"
version = "0.1.0"
edition = "2021"
description = "WASM Image Processor (resize)"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
thumbhash = "0.1.0"
base64 = "0.21"

# Optimization for size and speed
[profile.release]
opt-level = "s"   # Optimize for binary size
lto = true        # Link Time Optimization
strip = true      # Strip symbols
codegen-units = 1 # Maximize optimization at the cost of compile time
panic = "abort"   # Remove panic unwinding to save size

# Config to fix "Bulk memory operations" error with older wasm-opt versions
# We rely on rustc optimizations (opt-level = "s") which are sufficient.
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
