name: 🚀 Deploy Next.js to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          set -e

          cd ${{ secrets.DEPLOY_PATH }}

          # Update Repository
          git pull origin main

          # Istall Requirements and Build
          yarn install --frozen-lockfile
          yarn build

          # Restart pm2
          pm2 restart nextapp || pm2 start yarn --name nextapp -- start
          pm2 save
          EOF
